dataset:
  img_width: 640
  img_height: 512
  num_classes: 3
  class_names:
  - person
  - bicycle
  - car
  class_id_offset: 1
  train:
    rgb_dir: ../../FLIR/images/train/rgb
    ir_dir: ../../FLIR/images/train/thermal
    label_dir: ../../FLIR/labels/train/rgb
    max_samples: null
  validation:
    rgb_dir: ../../FLIR/images/val/rgb
    ir_dir: ../../FLIR/images/val/thermal
    label_dir: ../../FLIR/labels/val/rgb
    max_samples: null
  batch_size: 4
  num_workers: 0
  pin_memory: true
  transform_prob: 0.5
  augmentation:
    flip_prob: 0.5
    scale_range:
    - 0.5
    - 1.5
    scale_prob: 0.6
    rotate_range:
    - -20
    - 20
    rotate_prob: 0.5
    translate_range:
    - -0.15
    - 0.15
    translate_prob: 0.5
    brightness_prob: 0.5
    brightness_range:
    - 0.7
    - 1.3
    contrast_prob: 0.5
    contrast_range:
    - 0.7
    - 1.3
model:
  fusion_backbone: resnet34
  yolo_cfg: yolov5l.yaml
  pretrained_yolo: ./yolov5l.pt
  fusion_loss_weight: 1.0
  detection_loss_weight: 1.0
training:
  epochs: 200
  learning_rate: 0.0001
  fusion_lr: 0.0001
  detector_lr: 0.0001
  min_lr: 1.0e-05
  max_grad_norm: 10.0
  warmup_epochs: 5
  unfreeze_epoch: 20
  freeze_fusion_after_unfreeze: false
  optimizer: adamw
  weight_decay: 0.0001
  momentum: 0.937
  early_stopping:
    patience: 40
    min_delta: 0.0001
  val_interval: 1
  save_interval: 1
  accumulation_steps: 1
test:
  rgb_dir: ../FLIR/test/rgb
  ir_dir: ../FLIR/test/thermal
  label_dir: ../FLIR/test/labels/rgb
  max_samples: null
inference:
  confidence_threshold: 0.15
  iou_threshold: 0.45
  max_detections: null
output_dir: ./runs/TOOD_attention_model_v2
seed: 42
use_mmdet: true
mmdet_config: configs/tood_r50_fpn_1x_coco 1.py
mmdet_checkpoint: configs/tood_r50_fpn_1x_coco_20211210_103425-20e20746.pth
auto_adjust_class_weight: true
class_weight_update_interval: 10
